---
- name: Ouur first play
  hosts: planetexpress
  connection: ssh
  gather_facts: true
  become: yes # run as sudo

  tasks:
    - name: Install epel-release
      ansible.builtin.yum:
        name: epel-release
        state: present
      when: ansible_distribution == "CentOS"


    - name: Update yum repo, install package
      ansible.builtin.yum:
        update_cache: True
        name: 
          - fail2ban
          - moon-buggy
        state: latest
      when: ansible_distribution == "CentOS"

