---
- name: How to prompt for variables
  hosts: professors
  gather_facts: no

  vars_prompt:
    - name: "yourpassword"
      prompt: "What is your password?"
      private: yes
      

  tasks:
  - name: connect to the professors and install figlet
    yum:
      name: figlet
      state: present
    become: yes
