---
- name: Playbook that runs a Python script
  hosts: localhost

  tasks:
  - name: Copy script to target hosts and execute it
    ansible.builtin.uri: 
      url: http://api.open-notify.org/astros.json
    register: results    # save the JSON sent back by our script

  - name: Print
    ansible.builtin.debug:
      var: results